# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-cf:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - checkout
      - run: 
          name: Deploy Cloudformation Template
          command: |
            aws cloudformation create-stack \
            --template-body file://deploy-tap-eks.yaml \ 
            --stack-name taponeks01 \
            --parameters ParameterKey=RemoteAccessCidr,ParameterValue=0.0.0.0/0 ParameterKey=KeyPairName,ParameterValue=my-key  ParameterKey=EKSClusterName,ParameterValue=taponeks01   ParameterKey=TAPDomainName,ParameterValue=tap.buildcloudnativeapps.com      ParameterKey=TanzuNetUsername,ParameterValue=robinson039@gmail.com      ParameterKey=AvailabilityZones,ParameterValue=us-east-2b  ParameterKey=TanzuNetApiToken,ParameterValue=$TanzuNetApiToken    ParameterKey=TanzuNetPassword,ParameterValue=$TanzuNetPassword      ParameterKey=AcceptCEIP,ParameterValue=Yes  ParameterKey=AcceptEULAs,ParameterValue=Yes  
 
workflows:
  example-workflow:
    jobs:
      - deploy-cf