# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0.3

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-cf:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-cli/install
      - checkout
      - run: 
          name: Deploy Cloudformation Template
          command: |
            aws cloudformation deploy \
            --template aws-tap-entrypoint-new-vpc.template.yaml \
            --stack taponeks \
            --parameter-overrides ImageTag=${CIRCLE_SHA1}            
 
workflows:
  example-workflow:
    jobs:
      - deploy-cf